title: Aaron Cleveland
email: clevelandm.aaron@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software developer passionate about iOS, SwiftUI, and creating innovative
  solutions. Sharing insights on mobile development and product strategy.
baseurl: "" # keep empty when site is at domain root
url: "https://aaroncleveland.com"

# Beautiful Jekyll theme settings
author: Aaron Cleveland
social-network-links:
  twitter: notyourswiftdev
  github: notyourswiftdev

navbar-links:
  Home: "/"
  Resume: "/resume/"
  Portfolio: "/work/"
  Blog: "/blog/"
  Contact: "/contact/"

# Defaults so you don’t repeat front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
  - scope:
      path: ""
    values:
      layout: page

# Build settings
# remote_theme: daattali/beautiful-jekyll
# theme: minima
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"

# Permalinks
permalink: /blog/:year/:month/:day/:title/


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
